Remove the dependency on async-lock
smol-rs/blocking pull request #59
Opened 2024-04-21 21:54 UTC by james7132

This PR removes the need for async-lock as a dependency by making the Executor initializable in a const context. This relies on the const initialization of CondVars and Mutexes, so the MSRV was bumped to 1.63.

2024-04-21 22:16 UTC, notgull requested changes

2024-04-21 22:16 UTC, notgull commented on src/lib.rs
> +            .get_or_insert_with(|| NonZeroUsize::new(Self::max_threads()).unwrap())
Rather than having `unwrap` here, I would rather have `max_threads` return `NonZeroUsize`.

2024-04-21 23:52 UTC, james7132 commented on src/lib.rs
> +            .get_or_insert_with(|| NonZeroUsize::new(Self::max_threads()).unwrap())
Done.

2024-04-22 00:01 UTC, notgull requested changes
As an organization we maintain an MSRV policy where the MSRV should not exceed Debian Stable's packaged version of rustc. In this case this is 1.63.0. So we need to wait before this can be merged.

2024-04-22 00:18 UTC, taiki-e commented
> This relies on the const initialization of CondVars and Mutexes, so the MSRV was bumped to 1.68.

([const Mutex::new](https://doc.rust-lang.org/nightly/std/sync/struct.Mutex.html#method.new) and [const Condvar::new](https://doc.rust-lang.org/nightly/std/sync/struct.Condvar.html#method.new) are available since 1.63. That actually requires 1.68 is [const VecDeque::new](https://doc.rust-lang.org/nightly/std/collections/struct.VecDeque.html#method.new))

2024-05-13 07:16 UTC, james7132 commented
Found a way to lower the MSRV to 1.63 by using `Option<VecDeque<T>>` instead. This shouldn't need extra branches due to the niche layout optimization of VecDeque and Option.

2024-05-14 01:58 UTC, notgull approved these changes
Thanks!

2024-05-14 01:58 UTC, merged